NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

schedule:
    path:      /schedule
    defaults:  { _controller: ElskCoreBundle:Schedule:index }
