security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_LOCAL_ADMIN: [ROLE_USER, ROLE_LOCAL_ADMIN]
        ROLE_LOCAL_ADMIN: [ROLE_LOCAL_ADMIN, ROLE_GLOBAL_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_GLOBAL_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            security: false

        secured_area:
            - { path: ^/admin, roles: ROLE_LOCAL_ADMIN }
            - { path: ^/admin/register, roles: ROLE_GLOBAL_ADMIN }
            
