security:
    encoders:
        Elsk\ElskModelBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_API:         ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        db_provider:
            entity:
                class: ElskModelBundle:User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        wsse_secured:
            pattern:    ^/
            host:       api\.elsk\.dev
            stateless: true
            wsse:      true