# app/config/services.yml
services:
    Utilities:
        class: Elsk\CoreBundle\Services\Utilities

    ElskMailer:
        class: Elsk\CoreBundle\Services\Mailer
        arguments: ['@mailer']