Elsk\ElskModelBundle\Entity\Ability:
    type: entity
    table: ability
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        abilityName:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: ability_name
        isSpecialAbility:
            type: boolean
            nullable: false
            column: is_special_ability
    manyToMany:
        helpOffer:
            targetEntity: HelpOffer
            cascade: {  }
            fetch: LAZY
            mappedBy: ability
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
