Elsk\ElskModelBundle\Entity\ElskCity:
    type: entity
    table: elsk_city
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cityName:
            type: string
            nullable: false
            length: 17
            options:
                fixed: false
            column: city_name
        eventPeriodicity:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: event_periodicity
        nextEventDate:
            type: date
            nullable: false
            column: next_event_date
        createdAt:
            type: date
            nullable: false
            column: created_at
        updatedAt:
            type: date
            nullable: true
            column: updated_at
        deletedAt:
            type: date
            nullable: true
            column: deleted_at
    lifecycleCallbacks: {  }
