Elsk\ElskModelBundle\Entity\HelpOffer:
    type: entity
    table: help_offer
    uniqueConstraints:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        transport:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        helpCategory:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
            column: help_category
        comment:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        daysAvailable:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: days_available
        requestDate:
            type: datetime
            nullable: false
            column: request_date
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        ability:
            targetEntity: Ability
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: helpOffer
            joinTable:
                name: offer_ability
                joinColumns:
                    -
                        name: help_offer_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: ability_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
