Elsk\ElskModelBundle\Entity\Schedule:
    type: entity
    table: schedule
    uniqueConstraints:
        help_event_id:
            columns:
                - help_event_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: date
            nullable: false
            column: created_at
        updatedAt:
            type: date
            nullable: true
            column: updated_at
        deletedAt:
            type: date
            nullable: true
            column: deleted_at
    manyToOne:
        helpEvent:
            targetEntity: HelpEvent
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                help_event_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
