Elsk\ElskModelBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        city_id:
            columns:
                - elsk_city_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: last_name
        phone:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        isActive:
            type: boolean
            nullable: false
            column: is_active
        userType:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: user_type
        role:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    manyToOne:
        elskCity:
            targetEntity: ElskCity
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                elsk_city_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        emailGroup:
            targetEntity: EmailGroup
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_email_group
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: email_group_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
