Elsk\ElskModelBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cityId:
            type: integer
            column: city_id
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        login:
            type: string
            length: 255
    lifecycleCallbacks: {  }
