# app/config/services.yml
services:
    schedule.assignCategory:
        class: Elsk\ElskModelBundle\Schedule\ProcessUserRequest
        arguments: ['@doctrine.orm.entity_manager']
        public: false